<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Testing.Platform.MSBuild" Version="2.4.0" />
    <PackageReference Include="TUnit" Version="1.66.8" />
    <PackageReference Include="TUnit.Assertions" Version="1.66.8" />
    <PackageReference Include="TUnit.Engine" Version="1.66.8" />
    <PackageReference Include="NSubstitute" Version="6.2.0" />
    <PackageReference Include="Aspire.Hosting.AppHost" Version="13.5.3" />
    <PackageReference Include="Aspire.Hosting.Azure.ServiceBus" Version="13.5.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\AspireAsbEmulatorUi.Hosting\AspireAsbEmulatorUi.Hosting.csproj" />
    <ProjectReference Include="..\..\src\AspireAsbEmulatorUi.App\AspireAsbEmulatorUi.App.csproj" />
  </ItemGroup>

</Project>
